runtime: php
env: flex

runtime_config: document_root: public

# Ensure we skip ".env", which is only for local development
skip_files: 
    - .env

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 100

env_variables:
    # Put production environment variables here.
    APP_DEBUG: true
    APP_ENV: local
    APP_KEY: base64:yc797HuQTqYMXJPuUCo3sUe4iNZJYXFVf/lUH8/f1Lw=
    APP_NAME: "Laravel"

    LOG_LEVEL: debug
